### ISSUE TITLE
Failed and repeat logins

### ISSUE THREAD

**Issue by mkz212** [embee8/homebridge-panasonic-ac-platform#54] opened 2023-01-17 07:38 UTC
Hi. 

Plugin stop working today. I have correct version of Comfort Cloud in plugin settings. Comfort Cloud app is working ok. 

![0A6BA2BB-B943-4DE4-9C7F-5BB63CD398D2](https://user-images.githubusercontent.com/82271669/212837197-a5c017a6-06b6-439c-b46b-d060bfebbda4.jpeg)

**Comment by mkz212** [comment] 2023-01-17 10:25
Ok. Now even in Comford Cloud app I have internal server error E0011. 

But another things is that when plugin cannot connect to server it crash all homebridge (another plugins) and devices are unresponsible.

**Comment by clw123456** [comment] 2023-01-17 11:25
@mkz212 same here. I managed to resolve by manually updating the app version in the config to 1.17.0

**Comment by clw123456** [comment] 2023-01-17 11:25
@embee8 Hello! I see the latest app version is pulled through in the logs, should this auto update the config also or not? Thanks :)

**Comment by mkz212** [comment] 2023-01-17 12:02
I have 1.17.0 in config and still not working. But Comfort Cloud app also doesn’t work so it might be problem of the Comfort Cloud api.

**Comment by clw123456** [comment] 2023-01-17 12:12
Ah ok - comfort cloud working ok here in UK. Are you on latest version of the phone app?

**Comment by mkz212** [comment] 2023-01-17 12:14
iOS 1.17.0. Latest in App Store. In Poland.

**Comment by clw123456** [comment] 2023-01-17 12:18
Ok cool - maybe 2 seperate problems then! Hope your app comes back soon.

**Comment by magnusaurus** [comment] 2023-01-17 18:09
I am getting the same error message. I tried logging in with my dedicated homebridge account for Comfort Cloud but getting that same error message (E0011) when using that account. No issue to login to the app with my main account though. Seems strange

**Comment by duckdany** [comment] 2023-01-18 05:03
OK, the same is here.
Homebridge is not working with my secondary user. But I couldn't login also with my secondary user to the panasonic app too. (E0011 error) There is no problem with my main user. I could use app and homebridge too in the same time. Maybe it's a new feature. I don't know.

**Comment by mkz212** [comment] 2023-01-18 07:36
I tried on main Comfort Cloud account (i have only one) and have error E0011 or sometimes E0003. I tried reinstaling CC app. I tried changing version in this plugin config (I tried 1.18.0, 1.20.0, 2.0.0). Still not working.

**Comment by mkz212** [comment] 2023-01-18 07:41
I remember that in CC app was a message that in January will be some changes in CC app / API. So maybe this is it and we need to wait. But if that's the case, they could have done it more smoothly…

**Comment by mkz212** [comment] 2023-01-18 12:11
@embee8 Please do at least something so that it doesn't crash the whole homebridge system (offline cameras, devices not responding). It seems to me that the plugin tries to login to Comfort Cloud too often.

**Comment by mkz212** [comment] 2023-01-18 15:56
@magnusaurus If i disable plugin it will remove accessory from homekit and i need to setup automations from begining.

**Comment by magnusaurus** [comment] 2023-01-18 16:08
@mkz212 i hear you. but the developer of this plugin is probably doing this on spare time and it is completely free so it could take time to update this. if your homebridge instance is crashing, disabling the plugin temporarily seems like an acceptable compromise, no? 
I don’t know the details of your setup but I get the same log entry for failed login from CC but homebridge is not crashing because of it.

**Comment by mkz212** [comment] 2023-01-19 13:30
Finally I managed to find a solution. But it was a real road through torment.

I deleted my Panasonic ID and reinstalled - it didn't help. 

So I set up a new Panasonic ID. Then I had to reset the LAN settings of the A/C and add it to the new Panasonic Id.

But there is definitely something wrong with Comfort Cloud because I deleted my original Panasonic Id and when I wanted to change the e-mail from this new one to the old one, it shows that such an account already exists. So it seems that Panasonic is not completely deleting Panasonic Id account and some data is hanging there.

**Comment by mkz212** [comment] 2023-01-20 08:21
Returning for a moment to the problem of system blocking when the plugin cannot log in. According to the code, there should be one login attempt, then a pause (default 360 seconds) and so on until the correct login. For me, however, there were a lot attempts in the same second. Raspberry Pi temperature was rising by about 9-11 C. 

My soloution:
1. Fix the number of attempts. 
2. Option to set accessory as unbridge.

**Comment by Flemming-G-DK** [comment] 2023-01-21 19:42
I am experiencing the same issue as @mkz212.
After a failed login attempt I see an ever increasing number of login attempts that again are failing until homebridge crashes. 
For this reason I had to disable this plugin.
I suspect that the issue should be found in the method "loginAndDiscoverDevices" in "platform.ts" where a timer is spawned if login fails:

this._loginRetryTimeout = setInterval(this.loginAndDiscoverDevices.bind(this),
          LOGIN_RETRY_DELAY);

This timer is never cleared but still a new timer is spawned if login fails again. This causes a buildup of timers followed by an increasing number of new login attempts. 
I assume that clearing the timer in the beginning of "loginAndDiscoverDevices" should resolve the issue.
Something like:

for (const timeoutId of this._loginRetryTimeout) {
      clearTimeout(timeoutId);
    }

Unfortunately I'm not a node.js developer myself and therefore missing the skills and toolset for fixing this.
Anyone who can help?

**Comment by Flemming-G-DK** [comment] 2023-01-21 20:24
I agree :-)
Probably easier to switch to "setTimeout".
But I think the final fix should be done in src/platform.ts

**Comment by mkz212** [comment] 2023-01-21 20:28
src/ folder stands for source, and is the raw code before minification or concatenation or some other compilation - used to read/edit the code.

dist/ folder stands for distribution, and is the minified/concatenated version - actually used on production sites.

So you must change id dist folder.

**Comment by Mani1082** [comment] 2023-01-21 22:22
Hi guys, I cannot connect anymore to the comfort cloud anymore. I deleted all the accounts I had and when I create a new one, I will have to ask permission to the owner which is myself. 
I’m lost, I can’t creat a main account and can’t access my old main account because of error nº0003 or 0011. 
any idea how to fully reset all accounts to factory ?

**Comment by mkz212** [comment] 2023-01-22 07:33
1. Create new Panasonic ID. 
2. Reset LAN settings of your AC device. 
3. Add AC to new Panasonic ID.

**Comment by mkz212** [comment] 2023-01-22 07:36
@Flemming-G-DK 

Please let know if the change to „setTimout” fix the problem?

**Comment by Flemming-G-DK** [comment] 2023-01-22 08:41
@mkz212 
Last night I modified dist/platform.js to use setTimout instead of setInterval.
I reenabled the plugin and restarted homebridge.
In the log I see one successful login after restart.
Homebridge has been running without errors since that time.
I think the timer buildup is triggered by E0011 or E0003 from Panasonic Cloud and none of these has occurred.
So I really cannot tell what will happen.
However I'm pretty sure that the modification should prevent all these login attempts.
I will keep the system with this modification and get back if any errors occur.

**Comment by Mani1082** [comment] 2023-01-22 12:36
> @Mani1082
> 
> You must do this as completely new procedure, not sharing your device from existing Panasonic ID account.
> 
> 1. Create new Panasonic ID.
> 2. Reset LAN settings of your AC device.
> 3. Add AC to new Panasonic ID.
> 
> At least nothing else helped me.

Hi, that’s what I keep doing but it won’t let me be the main user. It will send a request to the main user. 
normally once the ac is factory reset there are no main users anymore. Am I missing something ?

**Comment by mkz212** [comment] 2023-01-22 12:48
@Mani1082 

Are you done this?

![AE2DB3D4-B32D-4F78-8D32-AEC73AE12FAE](https://user-images.githubusercontent.com/82271669/213916576-688816d2-cc57-41b0-8e8f-0b9ea7938c40.jpeg)

**Comment by Mani1082** [comment] 2023-01-22 13:16
Nice I didn’t know about the nº5 for lan reset
Thx

Le 22 janv. 2023 à 13:48, mkz212 ***@***.***> a écrit :

﻿

@Mani1082<https://github.com/Mani1082>

Are you done this?

[AE2DB3D4-B32D-4F78-8D32-AEC73AE12FAE]<https://user-images.githubusercontent.com/82271669/213916576-688816d2-cc57-41b0-8e8f-0b9ea7938c40.jpeg>

**Comment by Mani1082** [comment] 2023-01-22 13:25
> @Mani1082
> 
> Are you done this?
> 
> ![AE2DB3D4-B32D-4F78-8D32-AEC73AE12FAE](https://user-images.githubusercontent.com/82271669/213916576-688816d2-cc57-41b0-8e8f-0b9ea7938c40.jpeg)
> 
> 1. Push Wireless LAN button (bottom right on remote) for at least 5 seconds until You see 1 on remote display.
> 2. Use arrows to set 5
> 3. Confirm presing SET button for at least 3 seconds.

Finally I have a main account, you rock. 
can I add it to Homebridge directly or should I modify settings in the plugin ?

**Comment by mkz212** [comment] 2023-01-22 13:30
What do You mean directly or modify settings in the plugin? You can edit homebridge config or settings in plugin - results will be the same.

**Comment by Mani1082** [comment] 2023-01-22 13:35
> What do You mean directly or modify settings in the plugin? You can edit homebridge config or settings in plugin - results will be the same.

I have no idea how to access the .js file to add setTimeout, or I don’t need to modify anything else and can run the plugin with the new account

**Comment by mkz212** [comment] 2023-01-22 13:41
@Mani1082 You can run with new account.

@embee8 Please fix this issue by changing setInterval to setTimout in dist/platform.js

**Comment by Mani1082** [comment] 2023-01-22 13:44
> @Mani1082 You can run with new account. Just edit plugin settings or homebridge config.
> 
> @embee8 Please fix this issue by changing setInterval to setTimout in dist/platform.js

Thank you so much for the help
Everything is back to normal. 
✌🏼

**Comment by mkz212** [comment] 2023-01-22 14:24
If You want edit plugin code simplest way is go to Terminal and type: 

`sudo nano /usr/local/lib/node_modules/homebridge-panasonic-ac-platform/dist/platform.js`

and here change setInterval to setTimeout. Then restart homebridge.

**Comment by Mani1082** [comment] 2023-01-22 19:08
> If You want edit plugin to fix this, probably the simplest way is go to Terminal and type:
> 
> `sudo nano /usr/local/lib/node_modules/homebridge-panasonic-ac-platform/dist/platform.js`
> 
> Here change setInterval to setTimeout and save and restart homebridge.

👍🏼

**Comment by JurgenLB** [comment] 2023-01-22 19:17
For those wo have "Login Fail" I recommend putting Homebridge Panasonic AC platform as a "child Bridge", this way your other plugins can work even if this plugin Fails.

Also a reminder for everyone to check the APP in case of "Login Fail" for a "privacy Notice" to be accepted ! #53

**Comment by embee8** [comment] 2023-01-23 02:37
I believe @JurgenLB found the root cause of the recent increase in login errors. Despite using the latest app version, requests fail until the user accepts the latest terms and conditions in the main app.

This has stress-tested the plugin's ability to handle repeated login errors. There have been a few good discussions going on in here which led me to fix a bug.

I will also adapt the login behaviour to be less aggressive overall. It might require more user intervention (i.e. restarts) when the login fails because we will stop retrying after a few times, but the "kill switch" will also prevent Homebridge crashes due to memory leaks.

Patch release to follow shortly.

**Comment by mkz212** [comment] 2023-01-23 03:26
I believe that this is not a problem because I had accepted term. Nevertheless it was crashing homebridge. The problem stopped only after changing to setTimout, and it seems obvious that this must be the case. setTimeout sets one timer in 360 seconds, setInterval sets an infinite interval. I insist to change to setTimeout. And add text like „If you cannot log in, check if you have accepted the terms in the application”.

**Comment by embee8** [comment] 2023-01-23 03:57
The latest release should offer some stability improvements. I'm closing out the issue, but feel free to come back here or open a new one if any problems occur.

**Closed by embee8** 2023-01-23 03:57 UTC
